### ISSUE TITLE
States returned aren't valid JSON

### ISSUE THREAD

**Issue by l11111111111111** [warp-contracts/warp-contracts-cli#2]
The state returned by read commands aren't valid json but JS console.log on raw object output.

For example, when executing the command `warp read XIutiOKujGI21_ywULlBeyy-L9d8goHxt0ZyUayGaDg -eo allowBigInt`,
all the balances are `balances: [Object],`

**Comment by ppedziwiatr** [comment]
yeah, we should use `console.dir({depth: null})` here.
Keep in mind that you can also opt in to save the result in a file.

**Comment by l11111111111111** [comment]
console.dir would work against the `[Object]` problem but it would still not be valid JSON we could pipe to something else.
It could return something like `{foo:"bar"}` instead of `{"foo":"bar"}` for example.

I think it would be more practical to have actual JSON so we can then use jq to do whatever we need with it.

**Comment by ppedziwiatr** [comment]
ok, we will need to find a balance between..."entry-level" users, who don't even know about stuff like pipes and jq ;-) and simply want to quickly interact with a contract and see a nicely formatted and colored output - and those more advanced ones...
Maybe introducing some "silent" mode (that would remove logo, all the logs, etc. and would produce json output on... `process.stdout` I believe) is a way to go...
